# Generated by Django 5.2.3 on 2025-07-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('play_time', models.TimeField()),
                ('cover_image', models.ImageField(upload_to='BoardGame/')),
                ('category', models.CharField(choices=[('ST', 'Strategy'), ('FA', 'Family'), ('PA', 'Party'), ('CO', 'Cooperative'), ('CA', 'Card Game'), ('WA', 'War Game')], max_length=2)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOARD', 'Board'), ('CARD', 'Card'), ('TILE', 'Tile'), ('PAWN', 'Pawn'), ('DICE', 'Dice'), ('TOKEN', 'Token'), ('RULEBOOK', 'Rulebook'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='components/')),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('cost_value', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComponentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShelfLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='tutorial/videos/')),
                ('voice', models.FileField(blank=True, null=True, upload_to='tutorial/voices/')),
                ('status', models.CharField(choices=[('DR', 'draft'), ('PB', 'publish')], max_length=2)),
            ],
        ),
    ]
