# Generated by Django 5.2.3 on 2025-07-07 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boardgame', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardgamecomment',
            name='bordgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardgame.boardgame'),
        ),
        migrations.AddField(
            model_name='boardgamecomment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardgame.boardgamecomment'),
        ),
        migrations.AddField(
            model_name='boardgamecomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardgamecomponent',
            name='boardgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='boardgame.boardgame'),
        ),
        migrations.AddField(
            model_name='boardgamecomponent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardgameranking',
            name='boardgame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boardgame.boardgame'),
        ),
        migrations.AddField(
            model_name='boardgameranking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='componenttag',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='boardgame.boardgamecomponent'),
        ),
        migrations.AddField(
            model_name='componenttag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shelflocation',
            name='boardgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardgame.boardgame'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='boardgame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boardgame.boardgame'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
