# Generated by Django 5.2.3 on 2025-07-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
