# Generated by Django 5.2.3 on 2025-07-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0003_boardgame_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='is_active',
        ),
    ]
