# Generated by Django 5.2.3 on 2025-07-07 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0003_boardgame_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='is_active',
        ),
        migrations.AddConstraint(
            model_name='boardgame',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='unique_boardgame_name_per_user'),
        ),
    ]
